routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('auth.login');
// });

Auth::routes();

Route::namespace('Admin')->group(function () {
    Route::prefix('admin')->group(function () {
        Route::middleware('auth')->group(function () {
            Route::name('admin.')->group(function () {

                Route::prefix('users')->group(function () {
                    Route::name('users.')->group(function () {
                        Route::get('/', 'UserController@index')->name('index');
                        Route::get('/store', 'UserController@add')->name('add');
                        Route::post('/store', 'UserController@store')->name('store');
                        Route::get('/detail/{user}', 'UserController@detail')->name('edit');
                        Route::put('/update/{user}', 'UserController@update')->name('update');
                        Route::get('/edit-password/{user}', 'UserController@editPassword')->name('edit.password');
                        Route::put('/edit-password/{user}', 'UserController@updatePassword')->name('update.password');
                        Route::delete('/delete/{user}', 'UserController@delete')->name('delete');
                    });
                });

                Route::prefix('categories')->group(function () {
                    Route::name('categories.')->group(function () {
                        Route::get('/', 'CategoryController@index')->name('index');
                        Route::get('/store', 'CategoryController@add')->name('add');
                        Route::post('/store', 'CategoryController@store')->name('store');
                        Route::get('/detail/{category}', 'CategoryController@detail')->name('edit');
                        Route::put('/update/{category}', 'CategoryController@update')->name('update');
                        Route::delete('/delete/{category}', 'CategoryController@delete')->name('delete');
                    });
                });

                Route::prefix('products')->group(function () {
                    Route::name('products.')->group(function () {
                        Route::get('/', 'ProductController@index')->name('index');
                        Route::get('/store', 'ProductController@add')->name('add');
                        Route::post('/store', 'ProductController@store')->name('store');
                        Route::get('/detail/{product}', 'ProductController@detail')->name('edit');
                        Route::put('/update/{product}', 'ProductController@update')->name('update');
                        Route::delete('/delete/{product}', 'ProductController@delete')->name('delete');
                        Route::get('/change_status/{product}', 'ProductController@changeStatus')->name('change.status');
                    });
                });

                Route::prefix('projects_under_construction')->group(function () {
                    Route::name('projects_under_construction.')->group(function () {
                        Route::get('/', 'ProjectUnderConstructionController@index')->name('index');
                        Route::get('/store', 'ProjectUnderConstructionController@add')->name('add');
                        Route::post('/store', 'ProjectUnderConstructionController@store')->name('store');
                        Route::get('/detail/{project_building}', 'ProjectUnderConstructionController@detail')->name('edit');
                        Route::put('/update/{project_building}', 'ProjectUnderConstructionController@update')->name('update');
                        Route::delete('/delete/{project_building}', 'ProjectUnderConstructionController@delete')->name('delete');
                    });
                });

                Route::prefix('knowledges')->group(function () {
                    Route::name('knowledges.')->group(function () {
                        Route::get('/', 'KnowledgeController@index')->name('index');
                        Route::get('/store', 'KnowledgeController@add')->name('add');
                        Route::post('/store', 'KnowledgeController@store')->name('store');
                        Route::get('/detail/{knowledge}', 'KnowledgeController@detail')->name('edit');
                        Route::put('/update/{knowledge}', 'KnowledgeController@update')->name('update');
                        Route::delete('/delete/{knowledge}', 'KnowledgeController@delete')->name('delete');
                    });
                });

                Route::prefix('news')->group(function () {
                    Route::name('news.')->group(function () {
                        Route::get('/', 'NewsController@index')->name('index');
                        Route::get('/store', 'NewsController@add')->name('add');
                        Route::post('/store', 'NewsController@store')->name('store');
                        Route::get('/detail/{newspaper}', 'NewsController@detail')->name('edit');
                        Route::put('/update/{newspaper}', 'NewsController@update')->name('update');
                        Route::delete('/delete/{newspaper}', 'NewsController@delete')->name('delete');
                    });
                });

                Route::prefix('tags')->group(function () {
                    Route::name('tags.')->group(function () {
                        Route::get('/', 'TagController@index')->name('index');
                        Route::get('/store', 'TagController@add')->name('add');
                        Route::post('/store', 'TagController@store')->name('store');
                        Route::get('/detail/{tag}', 'TagController@detail')->name('edit');
                        Route::put('/update/{tag}', 'TagController@update')->name('update');
                        Route::delete('/delete/{tag}', 'TagController@delete')->name('delete');
                    });
                });

                Route::prefix('reviews')->group(function () {
                    Route::name('reviews.')->group(function () {
                        Route::get('/{rating_product?}', 'ReviewController@index')->name('index');
                        Route::get('/detail/{review}', 'ReviewController@detail')->name('edit');
                        Route::delete('/delete/{review}', 'ReviewController@delete')->name('delete');
                        Route::get('/change_status/{review}', 'ReviewController@changeStatus')->name('change.status');
                    });
                });

                Route::prefix('feedbacks')->group(function () {
                    Route::name('feedbacks.')->group(function () {
                        Route::get('/{news_id?}', 'FeedbackController@index')->name('index');
                        Route::delete('/delete/{feedback}', 'FeedbackController@delete')->name('delete');
                    });
                });
                
            });
        });
    });
});

Route::get('/home', 'HomeController@index')->name('home');

Route::name('public.')->group( function () {
    Route::get('/', 'IndexController@index')->name('home.index');
    Route::get('/gioi-thieu', 'IndexController@introduction')->name('introduction');
    Route::get('/chinh-sach-quy-dinh', 'IndexController@policyRegulation')->name('policy.regulation');
    Route::get('/danh-muc/{category}', 'CategoryController@detail')->name('category');
    Route::get('/san-pham/{product}', 'ProductController@detail')->name('product');
    Route::post('/review', 'ReviewController@store')->name('review.product');
    Route::get('/kien-thuc/{knowledge}', 'KnowledgeController@detail')->name('knowledge');
    Route::get('/kien-thuc/tin-tuc/{newspaper}', 'NewsController@detail')->name('news.detail');
    Route::post('/feedback', 'FeedbackController@store')->name('feedback');
    Route::get('/tags/{tag}', 'TagController@detail')->name('tags');
    Route::get('/du-an-dang-thi-cong', 'ProjectUnderConstructionController@index')->name('project.building.index');
    Route::get('/du-an-dang-thi-cong/{project_building}', 'ProjectUnderConstructionController@detail')->name('project_building.detail');
});

resources/views/frontend/index.blade.php
@extends('frontend.layouts.app')

@section('title', 'Công ty cổ phần LEDONE Việt Nam')


@section('content')

    <!-- Start Slider Area -->
    <div class="slider__container slider--one bg__cat--3">
        <div class="slide__container slider__activation__wrap owl-carousel">
            <!-- Start Single Slide -->
            @foreach($categories as $category)
                <div class="single__slide animation__style01 slider__fixed--height">
                    <div class="container">
                        <div class="row align-items__center">
                            <div class="col-md-7 col-sm-7 col-xs-12 col-lg-6">
                                <div class="slide">
                                    <div class="slider__inner">
                                        <h2>các dòng sản phẩm</h2>
                                        <h1 style="font-size:30px;">{{ strtoupper($category->name) }}</h1>
                                        <div class="cr__btn">
                                            <a href="{{ route('public.category', ['slug' => $category->slug ]) }}">Xem
                                                ngay</a>
                                        </div>
                                    </div>

                                </div>
                            </div>
                            <div class="col-lg-6 col-sm-5 col-xs-12 col-md-5">
                                <div class="slide__thumb">
                                    <img src="{{asset('storage/categories/'. $category->image)}}"
                                         alt="{{ $category->name }}">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        @endforeach
        <!-- End Single Slide -->
        </div>
    </div>
    <!-- Start Slider Area -->
    <!-- Start Category Area -->
    <section class="htc__category__area ptb--100">
        <div class="container">
            @forelse($categories as $category)
                @if(count($category->products))
                    <div class="row" style="margin-top: 30px;">
                        <div class="col-xs-12">
                            <div class="section__title--2 text-center">
                                <h2 class="title__line"><span><i class="fas fa-star"></i></span> &nbsp;
                                    &nbsp;{{ strtoupper($category->name) }}</h2>
                                <p>sản phẩm cùng thể loại</p>
                            </div>
                        </div>
                    </div>
                    <div class="htc__product__container">
                        <div class="row">
                            <div class="product__list clearfix mt--30">
                            @foreach($category->products as $product)
                                <!-- Start Single Category -->
                                    <div class="col-md-4 col-lg-3 col-sm-4 col-xs-12">
                                        <div class="category">
                                            <div class="ht__cat__thumb">
                                                <a href="{{ route('public.product', ['slug' => $product->slug ]) }}">
                                                    <img src="{{asset('storage/products/'. $product->image)}}"
                                                         alt="product images">
                                                </a>
                                            </div>
                                            <div class="fr__product__inner">
                                                <h4>
                                                    <a href="{{ route('public.product', ['slug' => $product->slug ]) }}">{{ $product->name }}</a>
                                                </h4>
                                                <ul class="fr__pro__prize">
                                                    @if($product->promotion == \App\Model\Product::PROMOTION)
                                                        <li class="old__prize">{{ number_format($product->price, 0 , ',', '.') }} vnđ</li>
                                                    @endif
                                                    <li>{{ number_format($product->price - $product->sale_off, 0 , ',', '.') }}vnđ
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                        <!-- End Single Category -->
                        <!-- End Single Category -->
                    </div>
                @endif
            @empty
            @endforelse

        </div>
    </section>
    <!-- End Category Area -->
    <!-- Start Prize Good Area -->
    <section class="htc__good__sale bg__cat--3">
        <div class="container">
            <div class="row">
                @if(!empty($knowledge))
                    <div class="col-md-6 col-lg-6 col-sm-6 col-xs-12">
                        <div class="fr__prize__inner">
                            <h2>{{ $knowledge->name }}</h2>
                            <h3>{{ $knowledge->desc }}</h3>
                            <a class="fr__btn" href="{{ route('public.knowledge', ['slug' => $knowledge->slug]) }}">Xem
                                thêm</a>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-6 col-sm-6 col-xs-12">
                        <div class="prize__inner">
                            <div class="prize__thumb">
                                <img src="{{asset('storage/knowledges/'. $knowledge->image)}}"
                                     alt="{{ $knowledge->name }}">
                            </div>
                        </div>
                    </div>
                @endif
            </div>
        </div>
    </section>
    <!-- End Prize Good Area -->
    <!-- Start Blog Area -->
    <section class="htc__blog__area bg__white ptb--100">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="section__title--2 text-center">
                        <h2 class="title__line">TIN TỨC</h2>
                        <p>Tin tức về sản phẩm và cách sử dụng</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="ht__blog__wrap clearfix">
                    <!-- Start Single Blog -->
                    @forelse($news as $newspaper)
                        <div class="col-md-6 col-lg-4 col-sm-6 col-xs-12">
                            <div class="blog">
                                <div class="blog__thumb">
                                    <a href="{{ route('public.news.detail',  ['slug' => $newspaper->slug]) }}">
                                        <img src="{{asset('storage/news/'. $newspaper->image)}}"
                                             alt="{{ $newspaper->name }}}">
                                    </a>
                                </div>
                                <div class="blog__details">
                                    <div class="bl__date">
                                        <span>{{ date_format(new DateTime($newspaper->updated_at), 'd-m-Y') }}</span>
                                    </div>
                                    <h2>
                                        <a href="{{ route('public.news.detail',  ['slug' => $newspaper->slug]) }}">{{ $newspaper->name }}</a>
                                    </h2>
                                    <p class="summary_public">{{ $newspaper->summary }}</p>
                                    <div class="blog__btn">
                                        <a href="{{ route('public.news.detail',  ['slug' => $newspaper->slug]) }}">Xem thêm</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @empty
                        <p>@lang('messages.no_data')</p>
                @endforelse
                <!-- End Single Blog -->
                </div>
            </div>
        </div>
    </section>
    <!-- End Blog Area -->
    <!-- End Product Area -->
    <!-- Start Testimonial Area -->
    <section class="htc__testimonial__area bg__cat--4">
        <div class="container">
            <h2 style="padding-top: 30px;" class="title__line text-center">DỰ ÁN ĐANG THI CÔNG</h2>
            <div class="row">
                <div class="ht__testimonial__activation clearfix">
                    <!-- Start Single Testimonial -->
                    @forelse(\App\Model\ProjectUnderConstruction::inRandomOrder()->take(DEFAULT_GET_ELEMENT)->get() as $puc)
                        <div class="col-lg-6 col-md-6 single__tes">
                            <div class="testimonial">
                                <div class="testimonial__thumb">
                                    <img src="{{asset('storage/projects_under_construction/'. $puc->image)}}"
                                         alt="{{ $puc->name }}">
                                </div>
                                <div class="testimonial__details">
                                    <h3 style="font-weight: bold">
                                        <a href="{{ route('public.project_building.detail', ['slug' => $puc->slug ]) }}">{{ $puc->name }}</a>
                                    </h3>
                                    <p style="overflow: hidden; text-overflow: ellipsis;  white-space: nowrap; width: 350px!important;">{{ $puc->summary }}</p>
                                </div>
                            </div>
                        </div>
                    @empty
                        <p>Không có dữ liệu</p>
                @endforelse
                <!-- End Single Testimonial -->

                </div>
            </div>
        </div>
    </section>
    <!-- End Testimonial Area -->
    <!-- Start Top Rated Area -->

    <!-- End Top Rated Area -->
    <!-- Start Brand Area -->
    <!-- End Brand Area -->

    <!-- End Banner Area -->
@endsection

resources/views/frontend/news-detail.blade.php
@extends('frontend.layouts.app')

@section('title',"$news->name | Công ty cổ phần công nghệ LEDONE Việt Nam")

@section('content')
    <div class="ht__bradcaump__area"
         style="background: rgba(0, 0, 0, 0) url('{{ asset('storage/news/'. $news->image) }}') no-repeat scroll center center / cover ;">
        <div class="ht__bradcaump__wrap">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="bradcaump__inner">
                            <nav class="bradcaump-inner">
                                <a class="breadcrumb-item" href="{{ route('public.home.index') }}">Trang chủ</a>
                                <span class="brd-separetor"><i class="zmdi zmdi-chevron-right"></i></span>
                                <span class="breadcrumb-item active">{{ $news->name }}</span>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <section class="htc__blog__details bg__white ptb--100">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-lg-12">
                    <div class="htc__blog__details__wrap">
                        <div class="ht__bl__thumb">
                            <img src="{{ asset('storage/news/'. $news->image) }}" alt="{{ $news->name }}">
                        </div>
                        <div class="bl__dtl">
                            {!! $news->desc !!}
                        </div>
                        <div class="sin__desc product__share__link">
                            <p><span>Chia sẻ:</span></p>
                            {!!
                                Share::currentPage(null, ['class' => 'my-class', 'id' => 'my-id'])
                                        ->facebook()
                                        ->twitter()
                                        ->googlePlus()
                            !!}
                        </div>
                        <!-- Start comment Form -->
                        <div class="ht__comment__form">
                            <form action="{{ route('public.feedback') }}" method="post">
                                @csrf
                                <h4 class="title__line--5">Phản hồi</h4>
                                <div class="ht__comment__form__inner">
                                    <div class="comment__form">
                                        <input type="text" name="name" value="{{ old('name') }}" placeholder="Name *">
                                        <input type="email" name="email" value="{{ old('email') }}" placeholder="Email *">
                                        <input type="text" value="{{ old('website_address') }}"  name="website_address" placeholder="Website">
                                        <input type="hidden" name="news_id"  value="{{ $news->id }}" placeholder="Website">
                                    </div>
                                    <div class="comment__form message">
                                        <textarea name="content" placeholder="Your Comment *">{{ old('website_address') }}</textarea>
                                    </div>
                                </div>
                                <div class="ht__comment__btn--2 mt--30">
                                    <button type="submit" class="fr__btn" href="#">Gửi</button>
                                </div>
                            </form>
                        </div>
                        <!-- End comment Form -->
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/frontend/news.blade.php
@extends('frontend.layouts.app')

@section('title',"$knowledge->name | Công ty cổ phần công nghệ LEDONE Việt Nam")


@section('content')
    <div class="ht__bradcaump__area"
         style="background: rgba(0, 0, 0, 0) url('{{ asset('storage/knowledges/'. $knowledge->image) }}') no-repeat scroll center center / cover ;">
        <div class="ht__bradcaump__wrap">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="bradcaump__inner">
                            <nav class="bradcaump-inner">
                                <a class="breadcrumb-item" href="{{ route('public.home.index') }}">Trang chủ</a>
                                <span class="brd-separetor"><i class="zmdi zmdi-chevron-right"></i></span>
                                <span class="breadcrumb-item active">{{ $knowledge->name }}</span>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <section class="htc__blog__area bg__white ptb--100">
        <div class="container">
            <div class="row">
                <div class="ht__blog__wrap blog--page clearfix">
                    <!-- Start Single Blog -->
                    @forelse($newspapers as $news)
                        <div class="col-md-6 col-lg-4 col-sm-12 col-xs-12">
                            <div class="blog">
                                <div class="blog__thumb">
                                    <a href="{{ route('public.news.detail', ['slug' => $news->slug]) }}">
                                        <img src="{{ asset('storage/news/'. $news->image) }}" alt="{{ $news->name }}">
                                    </a>
                                </div>
                                <div class="blog__details">
                                    <div class="bl__date">
                                        <span>{{ date_format(new DateTime($news->updated_at), 'd-m-Y') }}</span>
                                    </div>
                                    <h2><a href="{{ route('public.news.detail', ['slug' => $news->slug]) }}">{{ $news->name }}</a></h2>
                                    <p>{{ $news->summary }}</p>
                                    <div class="blog__btn">
                                        <a href="{{ route('public.news.detail', ['slug' => $news->slug]) }}">Xem thêm</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                @empty
                @endforelse
                <!-- End Single Blog -->
                </div>
            </div>
            <!-- Start PAgenation -->
            <div class="row">
                <div class="col-xs-12 text-center">
                    {{ $newspapers->links() }}
                </div>
            </div>
            <!-- End PAgenation -->
        </div>
    </section>
@endsection

resources/views/frontend/project-building-detail.blade.php
@extends('frontend.layouts.app')

@section('title',"$projectUnderConstruction->name")

@section('content')
<div class="container">
    <div class="ht__bradcaump__area"
    style="background: rgba(0, 0, 0, 0) url('{{ asset('storage/projects_under_construction/'. $projectUnderConstruction->image) }}') no-repeat scroll center center / cover ;">
   <div class="ht__bradcaump__wrap">
       <div class="container">
           <div class="row">
               <div class="col-xs-12">
                   <div class="bradcaump__inner">
                       <nav class="bradcaump-inner">
                           <a class="breadcrumb-item" href="{{ route('public.home.index') }}">Trang chủ</a>
                           <span class="brd-separetor"><i class="zmdi zmdi-chevron-right"></i></span>
                           <span class="breadcrumb-item active">{{ $projectUnderConstruction->name }}</span>
                       </nav>
                   </div>
               </div>
           </div>
       </div>
   </div>
</div>
<section class="htc__blog__details bg__white ptb--100">
   <div class="container">
       <div class="row">
           <div class="col-xs-12 col-lg-12">
               <div class="htc__blog__details__wrap">
                   <div class="ht__bl__thumb">
                       <img src="{{ asset('storage/projects_under_construction/'. $projectUnderConstruction->image) }}" alt="{{ $projectUnderConstruction->name }}">
                   </div>
                   <div class="bl__dtl">
                       {!! $projectUnderConstruction->desc !!}
                   </div>
               </div>
           </div>
       </div>
   </div>
   <div class="sin__desc product__share__link" style="margin-left: 1%;">
       <p><span>Chia sẻ:</span></p>
       {!!
           Share::currentPage(null, ['class' => 'my-class', 'id' => 'my-id'])
                   ->facebook()
                   ->twitter()
                   ->googlePlus()
       !!}
   </div>
</section>
</div>
   

@endsection

resources/views/frontend/project-building.blade.php
@extends('frontend.layouts.app')

@section('title',"Dự án thi công | Công ty cổ phần công nghệ LEDONE Việt Nam")

@section('content')
    <div class="container" style="margin-top: 20px;">
        <div class="row">
            @forelse($projectsUnderConstruction as $project)
                <div class="media table-hover">
                    <div class="media-left" style="width:20%">
                        <a href="{{ route('public.project_building.detail', ['slug' => $project->slug]) }}"><img src="{{asset('storage/projects_under_construction/'. $project->image) }}" class="{{ $project->name }}"></a>
                    </div>
                    <div class="media-body">
                        <h2 class="media-heading"><a href="{{ route('public.project_building.detail', ['slug' => $project->slug]) }}">{{ $project->name }}</a></h2>
                        <p>{{ $project->summary }}</p>
                    </div>
                    <div class="bl__date">
                        <span>{{ date_format(new DateTime($project->updated_at), 'd-m-Y') }}</span>
                    </div>
                </div>
                <hr>
            @empty
                <p>@lang('messages.no_data')</p>
            @endforelse
        </div>
    </div>
@endsection