routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('auth.login');
// });

Auth::routes();

Route::namespace('Admin')->group(function () {
    Route::prefix('admin')->group(function () {
        Route::middleware('auth')->group(function () {
            Route::name('admin.')->group(function () {

                Route::prefix('users')->group(function () {
                    Route::name('users.')->group(function () {
                        Route::get('/', 'UserController@index')->name('index');
                        Route::get('/store', 'UserController@add')->name('add');
                        Route::post('/store', 'UserController@store')->name('store');
                        Route::get('/detail/{user}', 'UserController@detail')->name('edit');
                        Route::put('/update/{user}', 'UserController@update')->name('update');
                        Route::get('/edit-password/{user}', 'UserController@editPassword')->name('edit.password');
                        Route::put('/edit-password/{user}', 'UserController@updatePassword')->name('update.password');
                        Route::delete('/delete/{user}', 'UserController@delete')->name('delete');
                    });
                });

                Route::prefix('categories')->group(function () {
                    Route::name('categories.')->group(function () {
                        Route::get('/', 'CategoryController@index')->name('index');
                        Route::get('/store', 'CategoryController@add')->name('add');
                        Route::post('/store', 'CategoryController@store')->name('store');
                        Route::get('/detail/{category}', 'CategoryController@detail')->name('edit');
                        Route::put('/update/{category}', 'CategoryController@update')->name('update');
                        Route::delete('/delete/{category}', 'CategoryController@delete')->name('delete');
                    });
                });

                Route::prefix('products')->group(function () {
                    Route::name('products.')->group(function () {
                        Route::get('/', 'ProductController@index')->name('index');
                        Route::get('/store', 'ProductController@add')->name('add');
                        Route::post('/store', 'ProductController@store')->name('store');
                        Route::get('/detail/{product}', 'ProductController@detail')->name('edit');
                        Route::put('/update/{product}', 'ProductController@update')->name('update');
                        Route::delete('/delete/{product}', 'ProductController@delete')->name('delete');
                        Route::get('/change_status/{product}', 'ProductController@changeStatus')->name('change.status');
                    });
                });

                Route::prefix('projects_under_construction')->group(function () {
                    Route::name('projects_under_construction.')->group(function () {
                        Route::get('/', 'ProjectUnderConstructionController@index')->name('index');
                        Route::get('/store', 'ProjectUnderConstructionController@add')->name('add');
                        Route::post('/store', 'ProjectUnderConstructionController@store')->name('store');
                        Route::get('/detail/{project_building}', 'ProjectUnderConstructionController@detail')->name('edit');
                        Route::put('/update/{project_building}', 'ProjectUnderConstructionController@update')->name('update');
                        Route::delete('/delete/{project_building}', 'ProjectUnderConstructionController@delete')->name('delete');
                    });
                });

                Route::prefix('knowledges')->group(function () {
                    Route::name('knowledges.')->group(function () {
                        Route::get('/', 'KnowledgeController@index')->name('index');
                        Route::get('/store', 'KnowledgeController@add')->name('add');
                        Route::post('/store', 'KnowledgeController@store')->name('store');
                        Route::get('/detail/{knowledge}', 'KnowledgeController@detail')->name('edit');
                        Route::put('/update/{knowledge}', 'KnowledgeController@update')->name('update');
                        Route::delete('/delete/{knowledge}', 'KnowledgeController@delete')->name('delete');
                    });
                });

                Route::prefix('news')->group(function () {
                    Route::name('news.')->group(function () {
                        Route::get('/', 'NewsController@index')->name('index');
                        Route::get('/store', 'NewsController@add')->name('add');
                        Route::post('/store', 'NewsController@store')->name('store');
                        Route::get('/detail/{newspaper}', 'NewsController@detail')->name('edit');
                        Route::put('/update/{newspaper}', 'NewsController@update')->name('update');
                        Route::delete('/delete/{newspaper}', 'NewsController@delete')->name('delete');
                    });
                });

                Route::prefix('tags')->group(function () {
                    Route::name('tags.')->group(function () {
                        Route::get('/', 'TagController@index')->name('index');
                        Route::get('/store', 'TagController@add')->name('add');
                        Route::post('/store', 'TagController@store')->name('store');
                        Route::get('/detail/{tag}', 'TagController@detail')->name('edit');
                        Route::put('/update/{tag}', 'TagController@update')->name('update');
                        Route::delete('/delete/{tag}', 'TagController@delete')->name('delete');
                    });
                });

                Route::prefix('reviews')->group(function () {
                    Route::name('reviews.')->group(function () {
                        Route::get('/{rating_product?}', 'ReviewController@index')->name('index');
                        Route::get('/detail/{review}', 'ReviewController@detail')->name('edit');
                        Route::delete('/delete/{review}', 'ReviewController@delete')->name('delete');
                        Route::get('/change_status/{review}', 'ReviewController@changeStatus')->name('change.status');
                    });
                });

                Route::prefix('feedbacks')->group(function () {
                    Route::name('feedbacks.')->group(function () {
                        Route::get('/{news_id?}', 'FeedbackController@index')->name('index');
                        Route::delete('/delete/{feedback}', 'FeedbackController@delete')->name('delete');
                    });
                });
                
            });
        });
    });
});

Route::get('/home', 'HomeController@index')->name('home');

Route::name('public.')->group( function () {
    Route::get('/', 'IndexController@index')->name('home.index');
    Route::get('/gioi-thieu', 'IndexController@introduction')->name('introduction');
    Route::get('/chinh-sach-quy-dinh', 'IndexController@policyRegulation')->name('policy.regulation');
    Route::get('/danh-muc/{category}', 'CategoryController@detail')->name('category');
    Route::get('/san-pham/{product}', 'ProductController@detail')->name('product');
    Route::post('/review', 'ReviewController@store')->name('review.product');
    Route::get('/kien-thuc/{knowledge}', 'KnowledgeController@detail')->name('knowledge');
    Route::get('/kien-thuc/tin-tuc/{newspaper}', 'NewsController@detail')->name('news.detail');
    Route::post('/feedback', 'FeedbackController@store')->name('feedback');
    Route::get('/tags/{tag}', 'TagController@detail')->name('tags');
    Route::get('/du-an-dang-thi-cong', 'ProjectUnderConstructionController@index')->name('project.building.index');
    Route::get('/du-an-dang-thi-cong/{project_building}', 'ProjectUnderConstructionController@detail')->name('project_building.detail');
});

app/Http/Controllers/Admin/TagController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Model\Tag;
use App\Repositories\Contract\TagRepository;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\AddTagRequest;
use App\Http\Requests\Admin\UpdateTagRequest;
use Illuminate\Http\Request;

class TagController extends Controller
{
    private $tagRepository;

    public function __construct()
    {
    	$this->tagRepository = app(TagRepository::class);
    }

    public function index(Request $request)
    {   
        if (isset($request->tags) && $request->has('tags'))
        {
            $tags = $this->tagRepository->findByName($request->tags);
        }else {
            $tags = $this->tagRepository->all();
        }
        return view('admin.tag.index', compact(['tags']));
    }

    public function add()
    {
        return view('admin.tag.add');
    }

    public function store(AddTagRequest $request)
    {
        $params = $request->all();
        $params['slug'] = str_slug($request->name);

        $this->tagRepository->create($params);

        return redirect()->back()->with('alert-success', trans('messages.success_created'));
    }

    public function detail(Tag $tag)
    {
        return view('admin.tag.edit', compact('tag'));
    }

    public function update(UpdateTagRequest $request, Tag $tag)
    {
        $data = $request->all();
        $data['slug'] = str_slug($request->name);

        $this->tagRepository->update($tag, $data);

        return redirect()->route('admin.tags.index')->with('alert-success', trans('messages.success_updated'));
    }

    public function delete(Tag $tag)
    {
        $this->tagRepository->destroy($tag);
        return redirect()->back()->with('alert-success', trans('messages.success_deleted'));
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Frontend\SortProductRequest;
use App\Model\Tag;
use App\Repositories\Contract\CategoryRepository;
use App\Repositories\Contract\ProductRepository;
use App\Repositories\Contract\TagRepository;
use App\Model\Product;

class TagController extends Controller
{
    private $categoryRepository;
    private $productRepository;
    private $tagRepository;
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->categoryRepository = app(CategoryRepository::class);
        $this->productRepository = app(ProductRepository::class);
        $this->tagRepository = app(TagRepository::class);
    }

    public function detail(Tag $tag, SortProductRequest $request)
    {
        $products = $this->productRepository->allWithBuilder()->where('tag_id', $tag->id)->where('status',Product::PUBLIC);
        
        if(isset($request->sort) && $request->has('sort')){
            $sortValue = $this->productRepository->sortUpdated_at($request->sort);
            $products = $products->orderBy('updated_at', $sortValue);
        }

        if(isset($request->sort_price_start) && isset($request->sort_price_end)) {
            $products = $products->whereBetween('price', [$request->sort_price_start, $request->sort_price_end]);
        }

        $products = $products->paginate(12);

        $categories = $this->categoryRepository->all();
        $tags = $this->tagRepository->allWithBuilder()->where('id','<>', $tag->id)->with('products')->get();
        return view('frontend.product-tag', compact(['products', 'tags', 'categories', 'tag']));
    }
}

resources/views/admin/tag/add.blade.php
@extends('adminlte::page')

@section('title', 'Thêm mới tag')

@section('content_header')
    <h1>Thêm tag</h1>
@stop

@section('content')

    <form action="{{ route('admin.tags.store') }}" method="POST">
        @csrf
        <div class="form-group">
            <label for="name">Tên: <span class="color-red">*</span></label>
            <input type="text" class="form-control" value="{{old('name')}}" name="name" id="name">
        </div>
        <button type="submit" class="btn btn-success">Thêm mới</button>
    </form>

@stop

@section('css')

    <link rel="stylesheet" href="/css/admin_custom.css">

@stop

@section('js')

@stop

resources/views/admin/tag/edit.blade.php
@extends('adminlte::page')

@section('title', 'Sửa tag')

@section('content_header')
    <h1>Sửa tag</h1>
@stop

@section('content')
    <form action="{{ route('admin.tags.update', ['slug' => $tag->slug]) }}" method="POST">
        @method('PUT')
        @csrf
        <div class="form-group">
            <label for="name">Tên: <span class="color-red">*</span></label>
            <input type="text" value=" {{ $tag->name  }} " class="form-control" name="name" id="name">
        </div>
        <button type="submit" class="btn btn-success">Cập nhật</button>
    </form>
@stop

@section('css')

    <link rel="stylesheet" href="/css/admin_custom.css">

@stop

@section('js')

@stop

resources/views/admin/tag/index.blade.php
@extends('adminlte::page')


@section('title', 'quản lý tag')

@section('content_header')
    <h1 class="inline">Danh sách các tag</h1>
    <a class="btn btn-info pull-right" href="{{ route('admin.tags.add') }}">Thêm tag mới</a>
@stop

@section('content')
    <p>Tìm kiếm</p>
    <div class="container-fluid">
        <div class="row">
        <form action="{{ route('admin.tags.index') }}" method="GET">
                <div class="input-group">
                    <input name="tag" type="text" class="form-control" placeholder="Search">
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>

        <div class="row">
            <div class="table-responsive">
                <table class="table table-bordred table-striped table-bordered">
                    <caption>Danh sách</caption>
                    <thead class="panel-title">
                    <tr>
                        <th scope="col">Stt</th>
                        <th scope="col">Tên</th>
                        <th scope="col">Sửa</th>
                        <th scope="col">Xóa</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $stt = 1;?>
                    @forelse($tags as $tag)
                        <tr>
                            <th scope="row">{{ $stt }}</th>
                            <td>{{ $tag->name }}</td>
                            <td>
                                <a href="{{ route('admin.tags.edit',['slug' => $tag->slug]) }}"
                                   class="btn btn-info"><i class="fas fa-edit">Sửa</i></a>
                            </td>
                            <td>
                                <form action="{{route('admin.tags.delete',['slug' => $tag->slug])}}"
                                      class="form-edit formConfirmDeleteTag" method="post">
                                    {{ method_field('DELETE') }}
                                    {{ csrf_field() }}
                                    <input type="submit" class="btn btn-danger submitDelete" value="Xóa">
                                </form>
                            </td>
                        </tr>
                        <?php $stt++;?>
                    @empty
                        <tr>
                            <td colspan="12" class="text-center">@lang('messages.no_data')</td>
                        </tr>
                    @endforelse

                    </tbody>
                </table>
            </div>
        </div>

    </div>

@stop

@section('css')

    <link rel="stylesheet" href="/css/admin_custom.css">

@stop

@section('js')
    <script src="{{asset('/js/ckeditor/ckeditor.js')}}"></script>
@stop