routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('auth.login');
// });

Auth::routes();

Route::namespace('Admin')->group(function () {
    Route::prefix('admin')->group(function () {
        Route::middleware('auth')->group(function () {
            Route::name('admin.')->group(function () {

                Route::prefix('users')->group(function () {
                    Route::name('users.')->group(function () {
                        Route::get('/', 'UserController@index')->name('index');
                        Route::get('/store', 'UserController@add')->name('add');
                        Route::post('/store', 'UserController@store')->name('store');
                        Route::get('/detail/{user}', 'UserController@detail')->name('edit');
                        Route::put('/update/{user}', 'UserController@update')->name('update');
                        Route::get('/edit-password/{user}', 'UserController@editPassword')->name('edit.password');
                        Route::put('/edit-password/{user}', 'UserController@updatePassword')->name('update.password');
                        Route::delete('/delete/{user}', 'UserController@delete')->name('delete');
                    });
                });

                Route::prefix('categories')->group(function () {
                    Route::name('categories.')->group(function () {
                        Route::get('/', 'CategoryController@index')->name('index');
                        Route::get('/store', 'CategoryController@add')->name('add');
                        Route::post('/store', 'CategoryController@store')->name('store');
                        Route::get('/detail/{category}', 'CategoryController@detail')->name('edit');
                        Route::put('/update/{category}', 'CategoryController@update')->name('update');
                        Route::delete('/delete/{category}', 'CategoryController@delete')->name('delete');
                    });
                });

                Route::prefix('products')->group(function () {
                    Route::name('products.')->group(function () {
                        Route::get('/', 'ProductController@index')->name('index');
                        Route::get('/store', 'ProductController@add')->name('add');
                        Route::post('/store', 'ProductController@store')->name('store');
                        Route::get('/detail/{product}', 'ProductController@detail')->name('edit');
                        Route::put('/update/{product}', 'ProductController@update')->name('update');
                        Route::delete('/delete/{product}', 'ProductController@delete')->name('delete');
                        Route::get('/change_status/{product}', 'ProductController@changeStatus')->name('change.status');
                    });
                });

                Route::prefix('projects_under_construction')->group(function () {
                    Route::name('projects_under_construction.')->group(function () {
                        Route::get('/', 'ProjectUnderConstructionController@index')->name('index');
                        Route::get('/store', 'ProjectUnderConstructionController@add')->name('add');
                        Route::post('/store', 'ProjectUnderConstructionController@store')->name('store');
                        Route::get('/detail/{project_building}', 'ProjectUnderConstructionController@detail')->name('edit');
                        Route::put('/update/{project_building}', 'ProjectUnderConstructionController@update')->name('update');
                        Route::delete('/delete/{project_building}', 'ProjectUnderConstructionController@delete')->name('delete');
                    });
                });

                Route::prefix('knowledges')->group(function () {
                    Route::name('knowledges.')->group(function () {
                        Route::get('/', 'KnowledgeController@index')->name('index');
                        Route::get('/store', 'KnowledgeController@add')->name('add');
                        Route::post('/store', 'KnowledgeController@store')->name('store');
                        Route::get('/detail/{knowledge}', 'KnowledgeController@detail')->name('edit');
                        Route::put('/update/{knowledge}', 'KnowledgeController@update')->name('update');
                        Route::delete('/delete/{knowledge}', 'KnowledgeController@delete')->name('delete');
                    });
                });

                Route::prefix('news')->group(function () {
                    Route::name('news.')->group(function () {
                        Route::get('/', 'NewsController@index')->name('index');
                        Route::get('/store', 'NewsController@add')->name('add');
                        Route::post('/store', 'NewsController@store')->name('store');
                        Route::get('/detail/{newspaper}', 'NewsController@detail')->name('edit');
                        Route::put('/update/{newspaper}', 'NewsController@update')->name('update');
                        Route::delete('/delete/{newspaper}', 'NewsController@delete')->name('delete');
                    });
                });

                Route::prefix('tags')->group(function () {
                    Route::name('tags.')->group(function () {
                        Route::get('/', 'TagController@index')->name('index');
                        Route::get('/store', 'TagController@add')->name('add');
                        Route::post('/store', 'TagController@store')->name('store');
                        Route::get('/detail/{tag}', 'TagController@detail')->name('edit');
                        Route::put('/update/{tag}', 'TagController@update')->name('update');
                        Route::delete('/delete/{tag}', 'TagController@delete')->name('delete');
                    });
                });

                Route::prefix('reviews')->group(function () {
                    Route::name('reviews.')->group(function () {
                        Route::get('/{rating_product?}', 'ReviewController@index')->name('index');
                        Route::get('/detail/{review}', 'ReviewController@detail')->name('edit');
                        Route::delete('/delete/{review}', 'ReviewController@delete')->name('delete');
                        Route::get('/change_status/{review}', 'ReviewController@changeStatus')->name('change.status');
                    });
                });

                Route::prefix('feedbacks')->group(function () {
                    Route::name('feedbacks.')->group(function () {
                        Route::get('/{news_id?}', 'FeedbackController@index')->name('index');
                        Route::delete('/delete/{feedback}', 'FeedbackController@delete')->name('delete');
                    });
                });
                
            });
        });
    });
});

Route::get('/home', 'HomeController@index')->name('home');

Route::name('public.')->group( function () {
    Route::get('/', 'IndexController@index')->name('home.index');
    Route::get('/gioi-thieu', 'IndexController@introduction')->name('introduction');
    Route::get('/chinh-sach-quy-dinh', 'IndexController@policyRegulation')->name('policy.regulation');
    Route::get('/danh-muc/{category}', 'CategoryController@detail')->name('category');
    Route::get('/san-pham/{product}', 'ProductController@detail')->name('product');
    Route::post('/review', 'ReviewController@store')->name('review.product');
    Route::get('/kien-thuc/{knowledge}', 'KnowledgeController@detail')->name('knowledge');
    Route::get('/kien-thuc/tin-tuc/{newspaper}', 'NewsController@detail')->name('news.detail');
    Route::post('/feedback', 'FeedbackController@store')->name('feedback');
    Route::get('/tags/{tag}', 'TagController@detail')->name('tags');
    Route::get('/du-an-dang-thi-cong', 'ProjectUnderConstructionController@index')->name('project.building.index');
    Route::get('/du-an-dang-thi-cong/{project_building}', 'ProjectUnderConstructionController@detail')->name('project_building.detail');
});

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\Contract\ProductRepository;
use App\Repositories\Contract\CategoryRepository;
use App\Repositories\Contract\TagRepository;
use App\Services\Helper;
use App\Services\Storages\StorageInterface;
use App\Services\Storages\LocalStorage;
use App\Http\Requests\Admin\AddProductRequest;
use App\Http\Requests\Admin\ProductUpdateStatusRequest;
use App\Http\Requests\Admin\UpdateProductRequest;
use App\Model\Product;

class ProductController extends Controller
{
    private $productRepository;
    private $categoryRepository;
    private $tagRepository;
    private $helperService;

    public function __construct()
    {
        $this->productRepository = app(ProductRepository::class);
        $this->categoryRepository = app(CategoryRepository::class);
        $this->tagRepository = app(TagRepository::class);
        $this->helperService = app(Helper::class);
    }

    public function index(Request $request)
    {   
        if (isset($request->products) && $request->has('products'))
        {
            $products = $this->productRepository->findByName($request->products);
        }else {
            $products = $this->productRepository->paginate();
        }

        return view('admin.product.index', compact('products'));
    }

    public function add()
    {
        $categories = $this->categoryRepository->all();
        $tags = $this->tagRepository->all();

        return view('admin.product.add', compact(['categories', 'tags']));
    }

    public function store(AddproductRequest $request)
    {
        $file = $request->file('image');
        $name = $this->createFileName($file);
        $this->uploadImage($file, $name, 'public/products', new LocalStorage);

        $params = $request->all();
        $params['slug'] = str_slug($request->name);
        $params['image'] = $name;

        $this->productRepository->create($params);

        return redirect()->back()->with('alert-success', trans('messages.success_created'));
    }

    public function detail(Product $product)
    {
        $categories = $this->categoryRepository->all();
        $tags = $this->tagRepository->all();

        return view('admin.product.edit', compact('product', 'tags', 'categories'));
    }

    public function update(UpdateproductRequest $request, Product $product)
    {
        $data = $request->all();
        $data['slug'] = str_slug($request->name);

        if ($request->hasFile('image')) {
            $name = $this->createFileName($request->image);
            $this->uploadImage($request->image, $name, 'public/products', new LocalStorage);
            $data['image'] = $name;
            @unlink('storage/products/'. $product->image);
        }

        $this->productRepository->update($product, $data);

        return redirect()->route('admin.products.index')->with('alert-success', trans('messages.success_updated'));
    }

    public function delete(Product $product)
    {
        $product->reviews()->forceDelete();
        $this->productRepository->destroy($product);
        @unlink('storage/products/'. $product->image);
        return redirect()->back()->with('alert-success', trans('messages.success_deleted'));
    }

    public function changeStatus(Product $product, ProductUpdateStatusRequest $request)
    {
        $data['status'] = ($request->status == Product::PUBLIC ) ? Product::UNPUBLIC : Product::PUBLIC;
        $this->productRepository->update($product, $data);

        return response()->json(['success'=> $data['status']]);
    }

    /**
     * Upload fileproduct
     * @param $file
     * @param $name
     * @param $path
     * @param StorageInterface $storage
     * @return mixed
     */
    private function uploadImage($file, $name, $path, StorageInterface $storage)
    {
        return $storage->saveAs($file, $name, $path);
    }

    private function createFileName($file)
    {
        $fileEtx = $file->getClientOriginalExtension();
        return $this->helperService->generateStringUUID().'.'.$fileEtx;
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Model\Product;
use App\Repositories\Contract\CategoryRepository;
use App\Repositories\Contract\ProductRepository;
use App\Repositories\Contract\TagRepository;

class ProductController extends Controller
{
    private $categoryRepository;
    private $productRepository;
    private $tagRepository;
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->categoryRepository = app(CategoryRepository::class);
        $this->productRepository = app(ProductRepository::class);
        $this->tagRepository = app(TagRepository::class);
    }

    public function detail(Product $product)
    {
        $list_products = $this->productRepository->allWithBuilder()->where([['category_id', $product->category_id], ['id','<>', $product->id]])->with('reviews')->get();
        $categories = $this->categoryRepository->allWithBuilder()->where('id', '<>', $product->category_id)->get();
        $tags = $this->tagRepository->all(['products']);
        return view('frontend.product-detail', compact(['product', 'list_products', 'categories', 'tags']));
    }
}

resources/views/admin/product/add.blade.php
@extends('adminlte::page')

@section('title', 'Thêm mới sản phẩm')

@section('content_header')
    <h1>Thêm sản phẩm</h1>
@stop

@section('content')

    <form action="{{ route('admin.products.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label for="name">Tên: <span class="color-red">*</span></label>
            <input type="text" class="form-control <?php echo $errors->has('name') ? 'input-error' : '';?>" value="{{old('name')}}" name="name">
        </div>
        <div class="form-group">
            <label for="name">Giá: <span class="color-red">*</span></label>
            <input type="text" class="form-control <?php echo $errors->has('price') ? 'input-error' : '';?>" value="{{old('price')}}" name="price">
        </div>
        <div class="form-group">
            <label for="">Trạng thái giá</label>
            <select class="form-control <?php echo $errors->has('partner') ? 'input-error' : '';?>" name="promotion">
                    <option value="{{ \App\Model\Product::UNPROMOTION }}" {{old('promotion') == \App\Model\Product::UNPROMOTION ?'selected':''}}>Không giảm giá</option>
                    <option value="{{ \App\Model\Product::PROMOTION }}"  {{old('promotion') == \App\Model\Product::PROMOTION ?'selected':''}}>Giảm giá</option>
            </select>
        </div>
        <div class="form-group">
            <label for="name">Giá giảm :</label>
            <input type="text" class="form-control <?php echo $errors->has('sale_off') ? 'input-error' : '';?>" value="{{old('sale_off')}}" name="sale_off" id="sale_off">
        </div>
        <div class="form-group">
            <label for="name">Hình ảnh : <span class="color-red">*</span></label>
            <input type="file" class="form-control <?php echo $errors->has('image') ? 'input-error' : '';?>" value="{{old('image')}}" name="image" id="image">
        </div>
        <div class="form-group">
            <label for="name">Tóm tắt: <span class="color-red">*</span></label>
            <textarea name="summary" class="form-control <?php echo $errors->has('summary') ? 'input-error' : '';?>" rows="5" id="summary"> {{ old('summary')}} </textarea>
        </div>
        <div class="form-group">
            <label for="name">Thể loại của sản phẩm: <span class="color-red">*</span></label>
            <select class="form-control data-select-all <?php echo $errors->has('category_id') ? 'input-error' : '';?>" name="category_id">
                @if(count($categories) > 0)
                    <option value="">{{trans('messages.choose_category')}}</option>
                    @foreach ($categories as $category)
                        <option value="{{$category->id}}" {{old('category_id') == $category->id ?'selected':''}}>{{$category->name}}</option>
                    @endforeach
                @else
                    <option value="">Không có thể loại nào</option>
                @endif
            </select>
        </div>
        <div class="form-group">
            <label for="name">Tags: <span class="color-red">*</span></label>
            <select class="form-control data-select-all <?php echo $errors->has('tag_id') ? 'input-error' : '';?>" name="tag_id">
                @if(count($tags) > 0)
                    <option value="0">{{trans('messages.choose_tag')}}</option>
                    @foreach ($tags as $tag)
                        <option value="{{$tag->id}}" {{old('tag_id') == $tag->id ?'selected':''}}>{{$tag->name}}</option>
                    @endforeach
                @else
                    <option value="">Không có thẻ tag nào</option>
                @endif
            </select>
        </div>
        <div class="form-group">
            <label for="name">Miêu tả: <span class="color-red">*</span></label>
            <textarea name="desc" id="text" rows="10" cols="80" class="<?php echo $errors->has('desc') ? 'input-error' : '';?>">
                {{old('desc')}}
            </textarea>
        </div>

        <div class="form-group">
            <label for="">Trạng thái: <span class="color-red">*</span></label>
            <select class="form-control <?php echo $errors->has('status') ? 'input-error' : '';?>" name="status">
                    <option value="{{ \App\Model\Product::UNPUBLIC }}" {{old('status') == \App\Model\Product::UNPUBLIC ?'selected':''}}>Chưa sẳn sàng public</option>
                    <option value="{{ \App\Model\Product::PUBLIC }}"  {{old('status') == \App\Model\Product::PUBLIC ?'selected':''}}>Public sản phẩm</option>
            </select>
        </div>

        <button type="submit" class="btn btn-success">Thêm mới</button>
    </form>

@stop

@section('css')

    <link rel="stylesheet" href="/css/admin_custom.css">

@stop

@section('js')

@stop

resources/views/admin/product/edit.blade.php
@extends('adminlte::page')

@section('title', 'Sửa sản phẩm')

@section('content_header')
    <h1>Sửa sản phẩm</h1>
@stop

@section('content')

    <form action="{{ route('admin.products.update', ['slug' => $product->slug ]) }}" method="POST" enctype="multipart/form-data">
        @method('PUT')
        @csrf
        <div class="form-group">
            <label for="name">Tên: <span class="color-red">*</span></label>
        <input type="text" class="form-control <?php echo $errors->has('name') ? 'input-error' : '';?>" value="{{ $product->name }}" name="name">
        </div>
        <div class="form-group">
            <label for="name">Giá: <span class="color-red">*</span></label>
            <input type="text" class="form-control <?php echo $errors->has('price') ? 'input-error' : '';?>" value="{{ $product->price }}" name="price">
        </div>
        <div class="form-group">
            <label for="">Trạng thái giá</label>
            <select class="form-control <?php echo $errors->has('partner') ? 'input-error' : '';?>" name="promotion">
                    <option value="{{ \App\Model\Product::UNPROMOTION }}" {{ $product->promotion == \App\Model\Product::UNPROMOTION ?'selected':''}}>Không giảm giá</option>
                    <option value="{{ \App\Model\Product::PROMOTION }}"  {{ $product->promotion == \App\Model\Product::PROMOTION ?'selected':''}}>Giảm giá</option>
            </select>
        </div>
        <div class="form-group">
            <label for="name">Giá giảm :</label>
            <input type="text" class="form-control <?php echo $errors->has('sale_off') ? 'input-error' : '';?>" value="{{ $product->sale_off}}" name="sale_off" id="sale_off">
        </div>
        <div class="form-group">
            <label for="name">Hình ảnh : <span class="color-red">*</span></label>
            <input type="file" class="form-control <?php echo $errors->has('image') ? 'input-error' : '';?>" value="{{old('image')}}" name="image" id="image">
            <p><img src="{{ asset('storage/products/'. $product->image)}}" class="img-thumbnail" alt="{{ $product->name }}" style="max-width: 200px; height: 100px;-o-object-fit: contain;"></p>
        </div>
        <div class="form-group">
            <label for="name">Tóm tắt: <span class="color-red">*</span></label>
        <textarea name="summary" class="form-control <?php echo $errors->has('summary') ? 'input-error' : '';?>" rows="5" id="summary"> {{ $product->summary}} </textarea>
        </div>
        <div class="form-group">
            <label for="name">Thể loại của sản phẩm: <span class="color-red">*</span></label>
            <select class="form-control data-select-all <?php echo $errors->has('category_id') ? 'input-error' : '';?>" name="category_id">
                @if(count($categories) > 0)
                    <option value="">{{trans('messages.choose_category')}}</option>
                    @foreach ($categories as $category)
                        <option value="{{$category->id}}" {{$product->category_id == $category->id ?'selected':''}}>{{$category->name}}</option>
                    @endforeach
                @else
                    <option value="">Không có thể loại nào</option>
                @endif
            </select>
        </div>
        <div class="form-group">
            <label for="name">Tags: <span class="color-red">*</span></label>
            <select class="form-control data-select-all <?php echo $errors->has('tag_id') ? 'input-error' : '';?>" name="tag_id">
                @if(count($tags) > 0)
                    <option value="">{{trans('messages.choose_tag')}}</option>
                    @foreach ($tags as $tag)
                        <option value="{{$tag->id}}" {{ $product->tag_id == $tag->id ?'selected':''}}>{{$tag->name}}</option>
                    @endforeach
                @else
                    <option value="">Không có thẻ tag nào</option>
                @endif
            </select>
        </div>
        <div class="form-group">
            <label for="name">Miêu tả: <span class="color-red">*</span></label>
            <textarea name="desc" id="text" rows="10" cols="80" class="<?php echo $errors->has('desc') ? 'input-error' : '';?>">
                {{ $product->desc }}
            </textarea>
        </div>

        <div class="form-group">
            <label for="">Trạng thái: <span class="color-red">*</span></label>
            <select class="form-control <?php echo $errors->has('status') ? 'input-error' : '';?>" name="status">
                    <option value="{{ \App\Model\Product::UNPUBLIC }}" {{ $product->status == \App\Model\Product::UNPUBLIC ?'selected':''}}>Chưa sẳn sàng public</option>
                    <option value="{{ \App\Model\Product::PUBLIC }}"  {{ $product->status == \App\Model\Product::PUBLIC ?'selected':''}}>Public sản phẩm</option>
            </select>
        </div>

        <button type="submit" class="btn btn-success">Chỉnh sửa</button>
    </form>
@stop

@section('css')

    <link rel="stylesheet" href="/css/admin_custom.css">

@stop

@section('js')

@stop

resources/views/admin/product/index.blade.php
@extends('adminlte::page')

@section('title', 'quản lý sản phẩm')

@section('content_header')
    <h1 class="inline">Danh sách các sản phẩm</h1>
    <a class="btn btn-info pull-right" href="{{ route('admin.products.add') }}">Thêm thể sản phẩm mới</a>
@stop

@section('content')
    <p>Tìm kiếm</p>
    <div class="container-fluid">
        <div class="row">
        <form action="{{ route('admin.products.index') }}" method="GET">
                <div class="input-group">
                    <input name="products" type="text" class="form-control" placeholder="Search">
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>

        <div class="row">
            <div class="table-responsive">
                <table class="table table-bordred table-striped table-bordered text-center">
                    <caption>Danh sách</caption>
                    <thead class="panel-title">
                    <tr>
                        <th scope="col">Stt</th>
                        <th scope="col">Tên</th>
                        <th scope="col">Thể loại sản phẩm</th>
                        <th scope="col">Giá</th>
                        <th scope="col">Giá sale</th>
                        <th scope="col">Hình ảnh</th>
                        <th scope="col">Trạng thái</th>
                        <th scope="col">Xem đánh giá</th>
                        <th scope="col">Xóa</th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($products as $product)
                        <tr>
                            <th scope="row">{{ $product->id }}</th>
                            <td>
                                <a data-toggle="tooltip" title="Sửa sẩn phẩm !" href="{{ route('admin.products.edit',['slug' => $product->slug]) }}">{{ $product->name}}</a>
                            </td>
                            <td>{{ $product->category->name }}</td>
                            <td>{{ number_format($product->price, 0 , ',', '.')}} vnđ</td>
                            <td>{!! ($product->promotion == App\Model\Product::UNPROMOTION) ? "không giảm giá" : number_format($product->price - $product->sale_off, 0 , ',', '.') . ' vnđ' !!}</td>
                            <td><img src="{{ asset('storage/products/'. $product->image)}}" style="max-width: 200px; height: 100px;-o-object-fit: contain;" class="img-thumbnail" alt="{{ $product->name }}"></td>
                            <td><a 
                            href="javascript:void(0)" 
                            onclick="changeStatus('{{ $product->slug }}');" 
                            data-toggle="tooltip" 
                            title="{{ $product->status == App\Model\Product::PUBLIC ? 'sản phẩm được kích hoạt' : 'sản phẩm chưa được kích hoạt'}}">
                            <i class="{{ ($product->status == App\Model\Product::PUBLIC) ? 'far fa-check-square fa-lg' : 'far fa-eye-slash'}}" 
                            id="{{ $product->slug }}"
                            data-value="{{ $product->status }}"
                            ></i></a></td>
                            <th><a data-toggle="tooltip" title="Xem đánh giá !" href="{{ route('admin.reviews.index', ['id'=> $product->id]) }}"><i class="fas fa-directions"></i></a></th>
                            <td>
                                <form action="{{route('admin.products.delete',['slug' => $product->slug])}}"
                                      class="form-edit formConfirmDeleteCat" method="post">
                                    {{ method_field('DELETE') }}
                                    {{ csrf_field() }}
                                    <input type="submit" class="btn btn-danger submitDelete" value="Xóa">
                                </form>
                            </td>
                        </tr>
                         
                    @empty
                        <tr>
                            <td colspan="12" class="text-center">@lang('messages.no_data')</td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
        </div>

    </div>

@stop

@section('css')

    <link rel="stylesheet" href="/css/admin_custom.css">

@stop

@section('js')
<script src="{{asset('/js/ckeditor/ckeditor.js')}}"></script>
<script src="{{ asset('js/custom_admin.js') }}"></script>
<script>
    function changeStatus(product) {
        var status = $('i#' + product).attr('data-value');
        $.ajax({
            url: "/admin/products/change_status/" + product,
            data: {status: status},
            type: "GET",    
            success:function(data){
                var status = data.success;
                $("i#" + product).attr('data-value', status);
                if(status == 0) {
                    $('i#' + product).removeClass('far fa-check-square fa-lg').addClass('far fa-eye-slash');
                    $('i#' + product).parents().attr('title','Sản phẩm không được kích hoạt !');
                }else {
                    $('i#' + product).removeClass('far fa-eye-slash').addClass('far fa-check-square fa-lg');
                    $('i#' + product).parents().attr('title','Sản phẩm được kích hoạt !');
                }
            },
            error: function(err){
                alert('Đã có lỗi xảy ra, vui lòng tải lại trang !');
            }
        });
    }
</script>
@stop