routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('auth.login');
// });

Auth::routes();

Route::namespace('Admin')->group(function () {
    Route::prefix('admin')->group(function () {
        Route::middleware('auth')->group(function () {
            Route::name('admin.')->group(function () {

                Route::prefix('users')->group(function () {
                    Route::name('users.')->group(function () {
                        Route::get('/', 'UserController@index')->name('index');
                        Route::get('/store', 'UserController@add')->name('add');
                        Route::post('/store', 'UserController@store')->name('store');
                        Route::get('/detail/{user}', 'UserController@detail')->name('edit');
                        Route::put('/update/{user}', 'UserController@update')->name('update');
                        Route::get('/edit-password/{user}', 'UserController@editPassword')->name('edit.password');
                        Route::put('/edit-password/{user}', 'UserController@updatePassword')->name('update.password');
                        Route::delete('/delete/{user}', 'UserController@delete')->name('delete');
                    });
                });

                Route::prefix('categories')->group(function () {
                    Route::name('categories.')->group(function () {
                        Route::get('/', 'CategoryController@index')->name('index');
                        Route::get('/store', 'CategoryController@add')->name('add');
                        Route::post('/store', 'CategoryController@store')->name('store');
                        Route::get('/detail/{category}', 'CategoryController@detail')->name('edit');
                        Route::put('/update/{category}', 'CategoryController@update')->name('update');
                        Route::delete('/delete/{category}', 'CategoryController@delete')->name('delete');
                    });
                });

                Route::prefix('products')->group(function () {
                    Route::name('products.')->group(function () {
                        Route::get('/', 'ProductController@index')->name('index');
                        Route::get('/store', 'ProductController@add')->name('add');
                        Route::post('/store', 'ProductController@store')->name('store');
                        Route::get('/detail/{product}', 'ProductController@detail')->name('edit');
                        Route::put('/update/{product}', 'ProductController@update')->name('update');
                        Route::delete('/delete/{product}', 'ProductController@delete')->name('delete');
                        Route::get('/change_status/{product}', 'ProductController@changeStatus')->name('change.status');
                    });
                });

                Route::prefix('projects_under_construction')->group(function () {
                    Route::name('projects_under_construction.')->group(function () {
                        Route::get('/', 'ProjectUnderConstructionController@index')->name('index');
                        Route::get('/store', 'ProjectUnderConstructionController@add')->name('add');
                        Route::post('/store', 'ProjectUnderConstructionController@store')->name('store');
                        Route::get('/detail/{project_building}', 'ProjectUnderConstructionController@detail')->name('edit');
                        Route::put('/update/{project_building}', 'ProjectUnderConstructionController@update')->name('update');
                        Route::delete('/delete/{project_building}', 'ProjectUnderConstructionController@delete')->name('delete');
                    });
                });

                Route::prefix('knowledges')->group(function () {
                    Route::name('knowledges.')->group(function () {
                        Route::get('/', 'KnowledgeController@index')->name('index');
                        Route::get('/store', 'KnowledgeController@add')->name('add');
                        Route::post('/store', 'KnowledgeController@store')->name('store');
                        Route::get('/detail/{knowledge}', 'KnowledgeController@detail')->name('edit');
                        Route::put('/update/{knowledge}', 'KnowledgeController@update')->name('update');
                        Route::delete('/delete/{knowledge}', 'KnowledgeController@delete')->name('delete');
                    });
                });

                Route::prefix('news')->group(function () {
                    Route::name('news.')->group(function () {
                        Route::get('/', 'NewsController@index')->name('index');
                        Route::get('/store', 'NewsController@add')->name('add');
                        Route::post('/store', 'NewsController@store')->name('store');
                        Route::get('/detail/{newspaper}', 'NewsController@detail')->name('edit');
                        Route::put('/update/{newspaper}', 'NewsController@update')->name('update');
                        Route::delete('/delete/{newspaper}', 'NewsController@delete')->name('delete');
                    });
                });

                Route::prefix('tags')->group(function () {
                    Route::name('tags.')->group(function () {
                        Route::get('/', 'TagController@index')->name('index');
                        Route::get('/store', 'TagController@add')->name('add');
                        Route::post('/store', 'TagController@store')->name('store');
                        Route::get('/detail/{tag}', 'TagController@detail')->name('edit');
                        Route::put('/update/{tag}', 'TagController@update')->name('update');
                        Route::delete('/delete/{tag}', 'TagController@delete')->name('delete');
                    });
                });

                Route::prefix('reviews')->group(function () {
                    Route::name('reviews.')->group(function () {
                        Route::get('/{rating_product?}', 'ReviewController@index')->name('index');
                        Route::get('/detail/{review}', 'ReviewController@detail')->name('edit');
                        Route::delete('/delete/{review}', 'ReviewController@delete')->name('delete');
                        Route::get('/change_status/{review}', 'ReviewController@changeStatus')->name('change.status');
                    });
                });

                Route::prefix('feedbacks')->group(function () {
                    Route::name('feedbacks.')->group(function () {
                        Route::get('/{news_id?}', 'FeedbackController@index')->name('index');
                        Route::delete('/delete/{feedback}', 'FeedbackController@delete')->name('delete');
                    });
                });
                
            });
        });
    });
});

Route::get('/home', 'HomeController@index')->name('home');

Route::name('public.')->group( function () {
    Route::get('/', 'IndexController@index')->name('home.index');
    Route::get('/gioi-thieu', 'IndexController@introduction')->name('introduction');
    Route::get('/chinh-sach-quy-dinh', 'IndexController@policyRegulation')->name('policy.regulation');
    Route::get('/danh-muc/{category}', 'CategoryController@detail')->name('category');
    Route::get('/san-pham/{product}', 'ProductController@detail')->name('product');
    Route::post('/review', 'ReviewController@store')->name('review.product');
    Route::get('/kien-thuc/{knowledge}', 'KnowledgeController@detail')->name('knowledge');
    Route::get('/kien-thuc/tin-tuc/{newspaper}', 'NewsController@detail')->name('news.detail');
    Route::post('/feedback', 'FeedbackController@store')->name('feedback');
    Route::get('/tags/{tag}', 'TagController@detail')->name('tags');
    Route::get('/du-an-dang-thi-cong', 'ProjectUnderConstructionController@index')->name('project.building.index');
    Route::get('/du-an-dang-thi-cong/{project_building}', 'ProjectUnderConstructionController@detail')->name('project_building.detail');
});

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\AddUserRequest;
use App\Http\Requests\Admin\UpdateUserPasswordRequest;
use App\Http\Requests\Admin\UpdateUserRequest;
use App\Repositories\Contract\UserRepository;
use App\Services\Helper;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Services\Storages\LocalStorage;
use App\Services\Storages\StorageInterface;
use App\Model\User;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    private $userRepository;
    private $helperService;

    public function __construct()
    {
        $this->userRepository = app(UserRepository::class);
        $this->helperService = app(Helper::class);
    }

    public function index(Request $request)
    {
        if (isset($request->users) && $request->has('users')) {
            $users = $this->userRepository->findByName($request->users);
        } else {
            $users = $this->userRepository->paginate();
        }

        return view('admin.user.index', compact(['users']));
    }

    public function add()
    {
        return view('admin.user.add');
    }

    public function store(AddUserRequest $request)
    {
        $file = $request->file('image');
        $name = $this->createFileName($file);
        $this->uploadImage($file, $name, 'public/users', new LocalStorage);

        $data = $request->all();
        $data['token_active'] = generateToken();
        $data['password'] = bcrypt($data['password']);
        $data['image'] = $name;

        $this->userRepository->create($data);
        return redirect()->back()->with('alert-success', trans('messages.success_created'));
    }

    public function detail(User $user)
    {
        return view('admin.user.edit', compact('user'));
    }

    public function update(UpdateUserRequest $request, User $user)
    {
        $data = $request->all();
        $data['email'] = $user->email;

        if ($request->hasFile('image')) {
            $name = $this->createFileName($request->image);
            $this->uploadImage($request->image, $name, 'public/users', new LocalStorage);
            $data['image'] = $name;
            @unlink('storage/users/' . $user->image);
            $data['image'] = $name;
        }

        $this->userRepository->update($user, $data);

        return redirect()->route('admin.users.edit', ['id' => $user->id])->with('alert-success', trans('messages.success_updated'));
    }

    public function editPassword(User $user)
    {
        return view('admin.user.edit-password', compact('user'));
    }

    public function updatePassword(UpdateUserPasswordRequest $request, User $user)
    {
        $current_password = Auth::user()->password;
        if(!Hash::check($request->old_password, $current_password)){
            return redirect()->back()->with('alert-error', trans('messages.updated_password_fail'));
        }

        $this->userRepository->update($user, ['password' => bcrypt($request->input('new_password'))]);

        if (auth()->user()->email == $user->email) {
            auth()->logout();
        }
        return redirect()->back()->with('alert-success', trans('messages.updated_success'));
    }

    public function delete(User $user)
    {
        if($user->id == auth()->id()){
            return abort(404);
        }
        $this->userRepository->destroy($user);
        return redirect()->back()->with('alert-success', trans('messages.success_deleted'));
    }

    /**
     * Upload fileproduct
     * @param $file
     * @param $name
     * @param $path
     * @param StorageInterface $storage
     * @return mixed
     */
    private function uploadImage($file, $name, $path, StorageInterface $storage)
    {
        return $storage->saveAs($file, $name, $path);
    }

    private function createFileName($file)
    {
        $fileEtx = $file->getClientOriginalExtension();
        return $this->helperService->generateStringUUID() . '.' . $fileEtx;
    }
}

resources/views/admin/user/add.blade.php
@extends('adminlte::page')

@section('title', 'Thêm người dùng')

@section('content_header')
    <h1>Thêm người dùng</h1>
@stop

@section('content')

    <form action="{{ route('admin.users.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label for="name">Tên: <span class="color-red">*</span></label>
            <input type="text" class="form-control <?php echo $errors->has('name') ? 'input-error' : '';?>" value="{{old('name')}}" name="name" id="name">
        </div>
        <div class="form-group">
            <label for="name">Email: <span class="color-red">*</span></label>
            <input type="text" class="form-control <?php echo $errors->has('email') ? 'input-error' : '';?>" value="{{old('email')}}" name="email" id="email">
        </div>
        <div class="form-group">
            <label for="name">Hình ảnh : <span class="color-red">*</span></label>
            <input type="file" class="form-control <?php echo $errors->has('image') ? 'input-error' : '';?>" value="{{old('image')}}" name="image" id="image">
        </div>
        <div class="form-group">
            <label for="password">Nhập mật khẩu</label>
            <input type="password" class="form-control <?php echo $errors->has('password') ? 'input-error' : '';?>" id="password" name="password" placeholder="Nhập mật khẩu">
        </div>

        <div class="form-group">
            <label for="password-confirm">Nhập mật khẩu</label>
            <input type="password" class="form-control <?php echo $errors->has('password_confirmation') ? 'input-error' : '';?>" id="password-confirm" name="password_confirmation" placeholder="Nhập lại mật khẩu">
        </div>
        <div class="form-group">
            <div class="form-group <?php echo $errors->has('sex') ? 'input-error' : '';?>">
                <label for="role">Giới tính</label>
                <select class="form-control" id="sex" name="sex">
                    <option value="{{\App\Model\User::MALE}}" {{\App\Model\User::MALE == old('sex') ? 'selected' : ''}}>Nam</option>
                    <option value="{{\App\Model\User::FEMALE}}" {{\App\Model\User::FEMALE == old('sex') ? 'selected' : ''}}>Nữ</option>
                </select>
            </div>
        </div>

        <button type="submit" class="btn btn-success">Thêm mới</button>
    </form>

@stop

@section('css')

    <link rel="stylesheet" href="/css/admin_custom.css">

@stop

@section('js')

@stop

resources/views/admin/user/edit-password.blade.php
@extends('adminlte::page')

@section('title', 'Đổi mật khẩu')

@section('content_header')
    <h1>Sửa mật khẩu</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Tài khoản</h4>
                    <form class="forms-sample" method="post" action="{{route('admin.users.update.password',['id' => $user->id])}}" enctype="multipart/form-data" id="edit_user">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="email">Địa chỉ email</label>
                            <input type="email" disabled class="form-control" id="email" value="{{$user->email }}" name="email">
                        </div>
                        <div class="form-group">
                            <label for="new_password">Nhập mật khẩu cũ</label>
                            <input type="password" class="form-control" id="old_password" value="{{ old('old_password') }}"  name="old_password" placeholder="Nhập mật khẩu cũ" >
                        </div>
                        <div class="form-group">
                            <label for="new_password">Nhập mật khẩu mới</label>
                            <input type="password" class="form-control" id="new_password" value="{{ old('new_password') }}" name="new_password" placeholder="Nhập mật khẩu mới" >
                        </div>
                        <div class="form-group">
                            <label for="confirm_password">Nhập lại mật khẩu</label>
                            <input type="password" class="form-control" id="confirm_password" value="{{ old('new_password_confirmation') }}" name="new_password_confirmation" placeholder="Nhập lại mật khẩu mới" >
                        </div>

                        <div class="form-group">
                            <label for="role">Hình ảnh</label>
                            <img src="{{asset('storage/users/'.(isset($user->image) ? $user->image : ''))}}" alt="{{isset($user->name) ? $user->name : ''}}" class="img img-responsive img-avatar" style="max-width: 300px;margin-bottom: 20px;">
                        </div>
                        <button type="submit" class="btn btn-success mr-2" >Chỉnh sửa</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/user/edit.blade.php
@extends('adminlte::page')

@section('title', 'Sửa người dùng')

@section('content_header')
    <h1 style="display: inline-block;">Sửa người dùng</h1>
    <a href="{{ route('admin.users.edit.password', ['id' => $user->id ]) }}" class="pull-right btn btn-danger">Thay đổi password</a>
@stop

@section('content')
    <form action="{{ route('admin.users.update', ['id' => $user->id]) }}" method="POST" enctype="multipart/form-data">
        @method('PUT')
        @csrf
        <div class="form-group">
            <label for="name">Tên: <span class="color-red">*</span></label>
            <input type="text" class="form-control" value="{{ $user->name}}" name="name" id="name">
        </div>
        <div class="form-group">
            <label for="email">Địa chỉ email</label>
            <input type="email" disabled class="form-control" id="email" value="{{$user->email}}" name="email"
                   placeholder="Nhập địa chỉ email">
        </div>
        <div class="form-group">
            <label for="name">Hình ảnh : <span class="color-red">*</span></label>
            <input type="file" class="form-control <?php echo $errors->has('image') ? 'input-error' : '';?>"
                   value="{{old('image')}}" name="image" id="image">
            <p><img src="{{ asset('storage/users/'. $user->image)}}" class="img-thumbnail" alt="{{ $user->name }}"
                    style="max-width: 200px; height: 100px;-o-object-fit: contain;"></p>
        </div>
        <div class="form-group">
            <div class="form-group">
                <label for="role">Giới tính</label>
                <select class="form-control" id="sex" name="sex">
                    <option value="{{\App\Model\User::MALE}}" {{\App\Model\User::MALE == $user->sex ? 'selected' : ''}}>
                        Nam
                    </option>
                    <option value="{{\App\Model\User::FEMALE}}" {{\App\Model\User::FEMALE == $user->sex ? 'selected' : ''}}>
                        Nữ
                    </option>
                </select>
            </div>
        </div>

        <button type="submit" class="btn btn-success">Cập nhật</button>
    </form>
@stop

@section('css')

    <link rel="stylesheet" href="/css/admin_custom.css">

@stop

@section('js')

@stop

resources/views/admin/user/index.blade.php
@extends('adminlte::page')

@section('title', 'quản lý người dùng')

@section('content_header')
    <h1 class="inline">Danh sách người dùng</h1>
    <a class="btn btn-info pull-right" href="{{ route('admin.users.add') }}">Thêm người dùng mới</a>
@stop

@section('content')
    <p>Tìm kiếm</p>
    <div class="container-fluid">
        <div class="row">
            <form action="{{ route('admin.users.index') }}" method="GET">
                <div class="input-group">
                    <input name="categories" type="text" class="form-control" placeholder="Search">
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>

        <div class="row">
            <div class="table-responsive">
                <table class="table table-bordred table-striped table-bordered text-center">
                    <caption>Danh sách</caption>
                    <thead class="panel-title">
                    <tr>
                        <th scope="col">Stt</th>
                        <th scope="col">Tên</th>
                        <th scope="col">Email</th>
                        <th scope="col">Sửa</th>
                        <th scope="col">Xóa</th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($users as $user)
                        <tr>
                            <th scope="row">{{ $user->id }}</th>
                            <td>{{ $user->name }}</td>
                            <td>
                                {{ $user->email }}
                            </td>
                            <td>
                                <a href="{{ route('admin.users.edit',['id' => $user->id]) }}"
                                   class="btn btn-info"><i class="fas fa-edit">Sửa</i></a>
                            </td>
                            <td>
                                @if(Auth::id() == $user->id)
                                    <button class="btn btn-dark" disabled>Xóa</button>
                                @else
                                    <form action="{{route('admin.users.delete',['id' => $user->id])}}"
                                          class="form-edit formConfirmDeleteCat" method="post">
                                        {{ method_field('DELETE') }}
                                        {{ csrf_field() }}
                                        <input type="submit" class="btn btn-danger submitDelete" value="Xóa">
                                    </form>
                                @endif
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="12" class="text-center">@lang('messages.no_data')</td>
                        </tr>
                    @endforelse

                    </tbody>
                </table>
            </div>
        </div>

    </div>

@stop

@section('css')

    <link rel="stylesheet" href="/css/admin_custom.css">

@stop

@section('js')
    <script src="{{asset('/js/ckeditor/ckeditor.js')}}"></script>
@stop